# Generated by Django 5.2.8 on 2025-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='SKU'),
        ),
    ]
