# Generated by Django 5.2.8 on 2025-11-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-sku'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
